### ISSUE TITLE
Flatten and Option results in broken types

### ISSUE THREAD

**Issue by Alfred-Mountfield** [madonoharu/tsify#10]
Discovered another strange edge-case today, see the following:
```rust
#[test]
fn test_flatten_optional() {
    #[derive(Tsify)]
    struct A {
        a: i32,
        b: String,
    }

    #[derive(Tsify)]
    struct B {
        #[tsify(optional)]
        #[serde(flatten)]
        extra: Option<A>,
        c: i32,
    }

    assert_eq!(
        B::DECL,
        indoc! {""}
    );
}
```

You get the generated type:
```ts
export interface B extends A | null {
    c: number;
}
```
which is invalid.

I suspect the way to solve this would be for `B` to become a type and to use `&` instead of `extends` so you could do something like:
```ts
type B = {

} & (A | {})
```

I'm not sure of a way to express this using interfaces, so I suspect this would be a pretty substantial change.

**Comment by madonoharu** [comment]
Thank you very much!
I will try to fix this as soon as possible.
