### ISSUE TITLE
Use of `null` rather than `undefined`

### ISSUE THREAD

**Issue by Alfred-Mountfield** [madonoharu/tsify#6]
I was running into an issue yesterday with adjacently tagged enums. If you have something like:
```rust
#[derive(Debug, Serialize, Deserialize, Tsify)]
#[serde(tag = "reason", content = "inner")]
pub enum ParseBaseUriError {
    MissingTrailingSlash,
    ...
}
```

Then the generated types have the following structure

```typescript
declare namespace ParseBaseUriError {
    export type MissingTrailingSlash = { reason: "MissingTrailingSlash"; inner: null };
    ...
```

The issue here is that the type suggests `inner` must be `null`, where in my testing, serializing these objects just leaves the field as `undefined`.

I've [got a branch where I've written a potential fix](https://github.com/hashdeps/tsify/tree/am/undefined-test), but I have a feeling it might be quite hacky and I may not understand the reasoning behind picking `null` originally. Is there a reason why this library chooses `null` for unit types rather than `undefined`? I tried thinking about this and I'm not sure which one I'd pick, as I suspect neither map perfectly.

That branch makes `inner` optional, while keeping the value of `null`. If that seems sensible I'm happy to open a PR.

**Comment by madonoharu** [comment]
This is completely my mistake.
The correct output would be `export type AdjacentUnit = { t: "Unit" };`.

PR is very, very welcome!

**Comment by Alfred-Mountfield** [comment]
I've just checked and it would seem like there's inconsistent behaviour, but I'm unsure how to reproduce at the moment.

I _think_ that `inner` might be serialized as `null` if going to `JsValue`, but left undefined if going to JSON through serde. I'm not entirely sure yet though.

My previous serialization strategy (which I've rebased and lost 😞) was definitely producing `{t: "Unit"}` but now that I'm calling `JsValue::from_serde` it would seem that it's producing a `null` value which is very confusing. (But means the types generated by `tsify` are 'correct')

```rust
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Tsify)]
#[serde(tag = "type", content = "inner")]
pub enum Result<T, E> {
    Ok(T),
    Err(E),
}

#[wasm_bindgen(skip_typescript)]
pub fn some_function(foo: &JsValue) -> JsValue {
    let validate_result: Result<(), _> = some_other_function(foo).into(); // note the unit type
    JsValue::from_serde(&validate_result).expect("failed to serialize result")
}
```

produces this in Javascript:
```typescript
{
  "inner": null,
  "type": "Ok"
}
```

Where it didn't in my code previously

**Comment by madonoharu** [comment]
```rs
enum Foo {
    Newtype(()),
    Unit,
}
```

In `serde`, `Newtype(())` and `Unit` are distinguished.
Since `Result::Ok(())` is a `Newtype`, this is the correct output.

Note, however, that the input side of `serde_json` does not distinguish between `null` and `undefined` by default.

**Comment by Alfred-Mountfield** [comment]
That makes sense, thank you. I guess we'd still like to see the interface changed for the adjacently tagged enum with unit variants

**Comment by madonoharu** [comment]
```ts
type AdjacentlyUnitStrictInputType = { t: "Unit"; c?: null };
type AdjacentlyUnitStrictOutputType = { t: "Unit" };
```

Currently, we have not implemented a function to distinguish between the two, so it is basically simpler to give priority to `OutputType` in such cases.

But I confess, I already break this rule with `#[serde(default)]` for convenience lol.
Yes, optional is convenient.
I think `{ t: "Unit"; c?: null };` is fine for now.

I suppose the ideal would be to distinguish them in some way.
